.gitignore
README.md
backend/db.js
backend/routes.js
backend/show.js
config/config-sample.js
db/tables.sql
db/test-data.sql
package.json

db schema (only one table for now) from live db, I'm afraid we need to modify it

First version of db connection

---

frontend/src/css/main.less
frontend/src/js/components/Contacts.jsx
frontend/src/js/components/Seat.jsx
frontend/src/js/components/SeatSelector.jsx
frontend/src/js/components/ShoppingCart.jsx
frontend/src/js/components/ShowSelector.jsx
frontend/src/js/components/Store.jsx

Full path visible for end-user, shopping cart

---

frontend/src/js/components/FinalConfirmation.jsx
frontend/src/js/components/Store.jsx

a more elegant solution can be done when the button is actually designed
to be something more than just a <a>-tag

prevent doubleclicking on 'Siirry maksamaan'

---

backend/order.js
frontend/src/js/components/Store.jsx
frontend/src/js/models/order.js

failure validation on preparePayment

---

frontend/src/js/components/SeatSelector.jsx
frontend/src/js/components/ShoppingCart.jsx
frontend/src/js/components/Store.jsx

- add reservation timeout to Store.jsx 
- show timeout time in ShoppingCart
- prevent user from adding/removing seats when seats have been reserved

Frontend timer

---

app.js
backend/order.js
backend/routes.js
config/config-sample.js
frontend/src/css/main.less
frontend/src/js-admin/collections/shows.js
frontend/src/js-admin/models/show.js
frontend/src/js/collections/shows.js
frontend/src/js/collections/tickets.js
frontend/src/js/components/Contacts.jsx
frontend/src/js/components/SeatSelector.jsx
frontend/src/js/components/Store.jsx
frontend/src/js/models/order.js
frontend/src/js/models/show.js
frontend/src/js/models/ticket.js
frontend/src/js/models/venue.js
gulpfile.js
prod.js

Still need to test the whole workflow once..

Changes required to make reverse proxy work

---

frontend/src/css/main.less
frontend/src/js/components/Seat.jsx
frontend/src/js/components/ShoppingCart.jsx
frontend/src/js/components/Store.jsx
frontend/src/js/components/Ticket.jsx

Please comment whether or not to include the last commit (3ef96db "optional: update seatmap on every seat-click")

Simultaneous reservation

---

backend/order.js
backend/venue.js
frontend/src/js/components/Seat.jsx
frontend/src/js/components/SeatSelector.jsx
frontend/src/js/components/ShoppingCart.jsx
frontend/src/js/components/Store.jsx
frontend/src/js/components/Ticket.jsx
frontend/src/js/models/ticket.js

- changes a bit the way backend handles and sends the seat information
- use the static venue seat info and show section info in frontend without copying those into another object
- the net effect is -7 lines, but I think this is simpler and less prone to errors 
- also should be easier to do unnumbered seats now

Refactor this.seats

---

frontend/src/js-admin/components/editables.tsx

feel free to suggest anything better, this was my first idea - let's make it visible that it's not initialized

empty option by default

---

backend/src/mail.ts
backend/src/order.ts
backend/src/ticket.ts
config/config-sample.js
package.json

This reverts commit 263581e9b675424b3c6110252ee11a6b47277c17.

Revert "Use Mailgun to send email"

---

frontend/src/css/admin.less
frontend/src/js-admin/components/Home.tsx
frontend/src/js-admin/components/OrderList.tsx
frontend/src/js-admin/utils.ts

- Added title to orderlist view that contains the show's name and time
- Added showtimes to the show list in admin ui main view

Change admin ui titles

---

backend/src/confluenceAuth.ts
backend/src/log.ts
config/config-sample.js
package.json

also changed auth fails to be warnings instead of errors

log errors also to a given email

---

backend/src/discountCode.ts
backend/src/order.ts
backend/src/routes.ts
build_tar.sh
db/evolutions/01_add_production_to_discount_code.sql
frontend/src/js-admin/components/DiscountCodes.tsx
frontend/src/js/components/Contacts.tsx
frontend/src/js/components/Store.tsx

not null, foreign key to nk2_productions.id

add column production_id to nk2_discount_codes and use it

---

README.md
package.json

This removes the need for user to install gulp globally.

Add also "dev" script to package.json

---

backend/src/discountCode.ts

Get all discount code query was broken on production server,
this is fix attempt for it, runs nicely on developement.

Fix get all discount codes query

---

config/public/frontend-sample.js
frontend/src/js/App.tsx
frontend/src/js/components/Store.tsx
frontend/src/js/event.ts
package.json
tslint.json
yarn.lock

Add FB Pixel event tracking

---

package.json
yarn.lock

Had been added by mistake, and does not work on Macs (depends on inotify)

Remove "dev" package

---

backend/src/order.ts

Fix issue with already cancelled payments

---

frontend/src/js/event.ts

Fix import issue with react-facebook-pixel

Fix react-facebook-pixel import

---

frontend/src/js/components/Contacts.tsx

Adds strict email validation based on html email form input definition.
See commit for details.
Fix #141

Add strict email validation to frontend

---

backend/src/info-list.ts
backend/src/order.ts
config/config-sample.js
frontend/src/js/components/Contacts.tsx

Applies mailgun based mailing list
TODO: In future add support for sending emails form admin panel
Fix #123

Feature info list

---

backend/src/order.ts
frontend/src/js-admin/components/Statistics.tsx

Fixes issues with statistics and unneccesary error logging

Feature 1.3.3 fixes

---

backend/src/db.ts
backend/src/order.ts
frontend/src/js/components/Seat.tsx
frontend/src/js/components/Store.tsx

Fix some frontend issues with helper function getting invalid input and remove uneccessary error logging from reserve tickets.

Feature 1.3.4 fixes

---

backend/src/payment/index.ts
backend/src/payment/providers/checkout-v3.ts
db/tables.sql
db/test-data.sql
frontend/src/js/components/Store.tsx

Add to group order button for admin and implement checkout check payment status feature.

Feature 1.3.5 update

---

frontend/src/css/main.less
frontend/src/js/components/Footer.tsx

- Add seller contact information
- Add selling policy
Closes #126

Add seller contact information and selling policy to lippukauppa.
